CREATE TABLE IDSEQUENCE(
	VAL BIGINT
);

CREATE TABLE QUESTION(
	ID BIGINT PRIMARY KEY,
	QUESTION_STRING VARCHAR(80) NOT NULL,
        CORRECT_ANSWER VARCHAR(80) NOT NULL
);

INSERT INTO IDSEQUENCE (VAL) VALUES (1000);

INSERT INTO QUESTION (ID, QUESTION_STRING, CORRECT_ANSWER) VALUES (1, 'Whose final film as director was Eyes Wide Shut?', 'Stanley Kubrick'); 
INSERT INTO QUESTION (ID, QUESTION_STRING, CORRECT_ANSWER) VALUES (2, 'Which year was the Unix operating system implemented in?', '1969');
