
DROP TABLE QUESTION;
DROP TABLE IDSEQUENCE;

CREATE TABLE IDSEQUENCE(
	VAL BIGINT
);

CREATE TABLE QUESTION(
      ID BIGINT PRIMARY KEY,
      QUESTION_STRING VARCHAR(80) NOT NULL,
      CORRECT_ANSWER VARCHAR(80) NOT NULL,
      INCORRECT_ANSWER_1 VARCHAR(80) NOT NULL,
      INCORRECT_ANSWER_2 VARCHAR(80) NOT NULL,
      INCORRECT_ANSWER_3 VARCHAR(80) NOT NULL
);

INSERT INTO IDSEQUENCE (VAL) VALUES (1000);

INSERT INTO QUESTION (ID, QUESTION_STRING, CORRECT_ANSWER, INCORRECT_ANSWER_1, INCORRECT_ANSWER_2, INCORRECT_ANSWER_3) 
VALUES (1, 'Whose final film as director was Eyes Wide Shut?', 'Stanley Kubrick', 'David Kronenberg', 'Alfred Hitchcock', 'Orson Welles'); 
INSERT INTO QUESTION (ID, QUESTION_STRING, CORRECT_ANSWER, INCORRECT_ANSWER_1, INCORRECT_ANSWER_2, INCORRECT_ANSWER_3) 
VALUES (2, 'Which year was the Unix operating system implemented in?', '1969', '1956', '1973', '1984');
INSERT INTO QUESTION (ID, QUESTION_STRING, CORRECT_ANSWER, INCORRECT_ANSWER_1, INCORRECT_ANSWER_2, INCORRECT_ANSWER_3) 
VALUES (3, 'How Many is 6x7', '42', '19', '73', '84');
INSERT INTO QUESTION (ID, QUESTION_STRING, CORRECT_ANSWER, INCORRECT_ANSWER_1, INCORRECT_ANSWER_2, INCORRECT_ANSWER_3) 
VALUES (4, 'What is the capital city of Germany', 'Berlin', 'Munich', 'Bern', 'Oslo');
INSERT INTO QUESTION (ID, QUESTION_STRING, CORRECT_ANSWER, INCORRECT_ANSWER_1, INCORRECT_ANSWER_2, INCORRECT_ANSWER_3) 
VALUES (5, 'When did the Apollo 11 land on the moon?', '1969', '1984', '1996', '1973');